In [1]:
import pandas as pd
import glob
import os
import requests

## Data Loading

In [2]:
all_dfs = []
for filename in glob.glob("../data/*.csv"):
    new_df = pd.read_csv(filename)
    all_dfs.append(new_df)
df = pd.concat(all_dfs)

In [3]:
df.to_parquet("../data/raw_data.parquet", index=False)

In [4]:
df = pd.read_parquet("../data/raw_data.parquet")

In [5]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,...,iso_region,municipality,scheduled_service,icao_code,iata_code,gps_code,local_code,home_link,wikipedia_link,keywords
0,9/1/2025 12:00:00 AM,AA,1.0,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,...,None,None,None,None,None,None,None,None,None,None
1,9/1/2025 12:00:00 AM,AA,10.0,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,...,None,None,None,None,None,None,None,None,None,None
2,9/1/2025 12:00:00 AM,AA,1002.0,MSN,"Madison, WI",WI,Wisconsin,CLT,"Charlotte, NC",NC,...,None,None,None,None,None,None,None,None,None,None
3,9/1/2025 12:00:00 AM,AA,1003.0,CLT,"Charlotte, NC",NC,North Carolina,MCI,"Kansas City, MO",MO,...,None,None,None,None,None,None,None,None,None,None
4,9/1/2025 12:00:00 AM,AA,1003.0,MCI,"Kansas City, MO",MO,Missouri,CLT,"Charlotte, NC",NC,...,None,None,None,None,None,None,None,None,None,None

In [6]:
df.shape

(9356296, 46)

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9356296 entries, 0 to 9356295
Data columns (total 46 columns):
 #   Column               Dtype
---  ------               -----
 0   FL_DATE              object
 1   OP_UNIQUE_CARRIER    object
 2   OP_CARRIER_FL_NUM    float64
 3   ORIGIN               object
 4   ORIGIN_CITY_NAME     object
 5   ORIGIN_STATE_ABR     object
 6   ORIGIN_STATE_NM      object
 7   DEST                 object
 8   DEST_CITY_NAME       object
 9   DEST_STATE_ABR       object
 10  DEST_STATE_NM        object
 11  CRS_DEP_TIME         float64
 12  DEP_DELAY            float64
 13  DEP_DELAY_NEW        float64
 14  DEP_DEL15            float64
 15  ARR_DELAY            float64
 16  ARR_DEL15            float64
 17  CANCELLED            float64
 18  DIVERTED             float64
 19  CRS_ELAPSED_TIME     float64
 20  DISTANCE             float64
 21  DISTANCE_GROUP       float64
 22  CARRIER_DELAY        float64
 23  WEATHER_DELAY        float64
 24  NAS_DELAY            float64
 25  SECURITY_DELAY       float64
 26  LATE_AIRCRAFT_DELAY  float64
 27  id                   float64
 28  ident                object
 29  type                 object
 30  name                 object
 31  latitude_deg         float64
 32  longitude_deg        float64
 33  elevation_ft         float64
 34  continent            object
 35  iso_country          object
 36  iso_region           object
 37  municipality         object
 38  scheduled_service    object
 39  icao_code            object
 40  iata_code            object
 41  gps_code             object
 42  local_code           object
 43  home_link            object
 44  wikipedia_link       object
 45  keywords             object
dtypes: float64(21), object(25)
memory usage: 3.2+ GB
None

In [8]:
print(df.head())

                FL_DATE OP_UNIQUE_CARRIER  OP_CARRIER_FL_NUM ORIGIN  \
0  9/1/2025 12:00:00 AM                AA                1.0    JFK
1  9/1/2025 12:00:00 AM                AA               10.0    LAX
2  9/1/2025 12:00:00 AM                AA             1002.0    MSN
3  9/1/2025 12:00:00 AM                AA             1003.0    CLT
4  9/1/2025 12:00:00 AM                AA             1003.0    MCI

  ORIGIN_CITY_NAME ORIGIN_STATE_ABR ORIGIN_STATE_NM DEST   DEST_CITY_NAME  \
0     New York, NY               NY        New York  LAX  Los Angeles, CA
1  Los Angeles, CA               CA      California  JFK     New York, NY
2      Madison, WI               WI       Wisconsin  CLT    Charlotte, NC
3    Charlotte, NC               NC  North Carolina  MCI  Kansas City, MO
4  Kansas City, MO               MO        Missouri  CLT    Charlotte, NC

  DEST_STATE_ABR  ... iso_region  municipality  scheduled_service  icao_code  \
0             CA  ...       None          None               None       None
1             NY  ...       None          None               None       None
2             NC  ...       None          None               None       None
3             MO  ...       None          None               None       None
4             NC  ...       None          None               None       None

   iata_code  gps_code  local_code  home_link  wikipedia_link  keywords
0       None      None        None       None            None      None
1       None      None        None       None            None      None
2       None      None        None       None            None      None
3       None      None        None       None            None      None
4       None      None        None       None            None      None

[5 rows x 46 columns]

In [9]:
print(df.describe())

       OP_CARRIER_FL_NUM  CRS_DEP_TIME     DEP_DELAY  DEP_DELAY_NEW  \
count       9.270680e+06  9.270680e+06  9.113111e+06   9.113111e+06
mean        2.526089e+03  1.323805e+03  1.345565e+01   1.697300e+01
std         1.630858e+03  4.917860e+02  5.784014e+01   5.665760e+01
min         1.000000e+00  1.000000e+00 -1.150000e+02   0.000000e+00
25%         1.207000e+03  9.040000e+02 -6.000000e+00   0.000000e+00
50%         2.275000e+03  1.317000e+03 -2.000000e+00   0.000000e+00
75%         3.662000e+03  1.735000e+03  1.000000e+01   1.000000e+01
max         9.914000e+03  2.400000e+03  4.352000e+03   4.352000e+03

          DEP_DEL15     ARR_DELAY     ARR_DEL15     CANCELLED      DIVERTED  \
count  9.113111e+06  9.082564e+06  9.082564e+06  9.270680e+06  9.270680e+06
mean   2.171583e-01  8.041717e+00  2.207319e-01  1.761295e-02  2.678444e-03
std    4.123113e-01  6.005347e+01  4.147401e-01  1.315399e-01  5.168434e-02
min    0.000000e+00 -1.280000e+02  0.000000e+00  0.000000e+00  0.000000e+00
25%    0.000000e+00 -1.600000e+01  0.000000e+00  0.000000e+00  0.000000e+00
50%    0.000000e+00 -6.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%    0.000000e+00  1.100000e+01  0.000000e+00  0.000000e+00  0.000000e+00
max    1.000000e+00  4.336000e+03  1.000000e+00  1.000000e+00  1.000000e+00

       CRS_ELAPSED_TIME  ...  DISTANCE_GROUP  CARRIER_DELAY  WEATHER_DELAY  \
count      9.270677e+06  ...    9.270680e+06   2.004812e+06   2.004812e+06
mean       1.496883e+02  ...    3.853087e+00   2.414747e+01   4.669049e+00
std        7.308230e+01  ...    2.355503e+00   7.618385e+01   3.572687e+01
min       -9.900000e+01  ...    1.000000e+00   0.000000e+00   0.000000e+00
25%        9.500000e+01  ...    2.000000e+00   0.000000e+00   0.000000e+00
50%        1.340000e+02  ...    3.000000e+00   2.000000e+00   0.000000e+00
75%        1.800000e+02  ...    5.000000e+00   2.100000e+01   0.000000e+00
max        1.510000e+03  ...    1.100000e+01   4.336000e+03   2.394000e+03

          NAS_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY             id  \
count  2.004812e+06    2.004812e+06         2.004812e+06   85616.000000
mean   1.559351e+01    1.049984e-01         2.837938e+01  206159.198409
std    3.609325e+01    3.499826e+00         6.178817e+01  199834.731813
min    0.000000e+00    0.000000e+00         0.000000e+00       2.000000
25%    0.000000e+00    0.000000e+00         0.000000e+00   21560.750000
50%    1.000000e+00    0.000000e+00         1.000000e+00   45793.500000
75%    1.900000e+01    0.000000e+00         3.300000e+01  343738.250000
max    1.706000e+03    1.600000e+03         2.425000e+03  609466.000000

       latitude_deg  longitude_deg  elevation_ft
count  85616.000000   85616.000000  70764.000000
mean      25.817172     -27.377679   1292.497470
std       26.224024      85.212687   1657.003804
min      -90.000000    -179.876999  -1266.000000
25%       11.013100     -92.848250    208.000000
50%       35.157928     -63.567702    728.000000
75%       43.110324      23.670969   1608.000000
max       83.091029     179.975700  17372.000000

[8 rows x 21 columns]

In [10]:
missing_values = df.isnull().sum().sort_values(ascending=False)

In [11]:
missing_values

home_link              9351564
iata_code              9347241
icao_code              9346077
wikipedia_link         9339587
keywords               9334863
local_code             9320315
gps_code               9311958
continent              9310300
elevation_ft           9285532
municipality           9275387
iso_country            9270983
iso_region             9270680
scheduled_service      9270680
longitude_deg          9270680
latitude_deg           9270680
name                   9270680
type                   9270680
ident                  9270680
id                     9270680
NAS_DELAY              7351484
LATE_AIRCRAFT_DELAY    7351484
SECURITY_DELAY         7351484
WEATHER_DELAY          7351484
CARRIER_DELAY          7351484
ARR_DEL15               273732
ARR_DELAY               273732
DEP_DELAY               243185
DEP_DEL15               243185
DEP_DELAY_NEW           243185
CRS_ELAPSED_TIME         85619
DEST_CITY_NAME           85616
OP_CARRIER_FL_NUM        85616
ORIGIN                   85616
ORIGIN_CITY_NAME         85616
ORIGIN_STATE_ABR         85616
ORIGIN_STATE_NM          85616
DEST                     85616
OP_UNIQUE_CARRIER        85616
DEST_STATE_ABR           85616
DEST_STATE_NM            85616
CRS_DEP_TIME             85616
CANCELLED                85616
DIVERTED                 85616
DISTANCE                 85616
DISTANCE_GROUP           85616
FL_DATE                  85616
dtype: int64

## Data Preprocessing

In [12]:
import numpy as np

In [13]:
# Group 1 - Delay Cause Columns (Fill with 0 - missing simply means that delay cause didn't apply to that flight)
delay_cause_columns = ['LATE_AIRCRAFT_DELAY', 'SECURITY_DELAY', 'NAS_DELAY', 'WEATHER_DELAY', 'CARRIER_DELAY']
df[delay_cause_columns] = df[delay_cause_columns].fillna(0)

In [14]:
# Group 2 - Arrival Columns (Filter out cancelled and diverted flights)
df = df[df['CANCELLED'] == 0]
df = df[df['DIVERTED'] == 0]

In [15]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,...,iso_region,municipality,scheduled_service,icao_code,iata_code,gps_code,local_code,home_link,wikipedia_link,keywords
0,9/1/2025 12:00:00 AM,AA,1.0,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,...,None,None,None,None,None,None,None,None,None,None
1,9/1/2025 12:00:00 AM,AA,10.0,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,...,None,None,None,None,None,None,None,None,None,None
2,9/1/2025 12:00:00 AM,AA,1002.0,MSN,"Madison, WI",WI,Wisconsin,CLT,"Charlotte, NC",NC,...,None,None,None,None,None,None,None,None,None,None
3,9/1/2025 12:00:00 AM,AA,1003.0,CLT,"Charlotte, NC",NC,North Carolina,MCI,"Kansas City, MO",MO,...,None,None,None,None,None,None,None,None,None,None
4,9/1/2025 12:00:00 AM,AA,1003.0,MCI,"Kansas City, MO",MO,Missouri,CLT,"Charlotte, NC",NC,...,None,None,None,None,None,None,None,None,None,None

In [16]:
df.shape

(9082565, 46)

In [17]:
# Group 3 - Departure Target Columns (Drop these rows -- no target variable means the row is useless for training)
df = df[df['DEP_DELAY'].notna()]
df = df[df['DEP_DEL15'].notna()]
df = df[df['DEP_DELAY_NEW'].notna()]

In [18]:
df = df.dropna(subset=['ARR_DELAY'])
df = df.dropna(subset=['ARR_DEL15'])

In [19]:
# Group 4 - CRS_ELAPSED_TIME (Drop the 3 rows with missing values)
df = df[df['CRS_ELAPSED_TIME'].notna()]

In [20]:
df.shape

(9082563, 46)

In [21]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,...,iso_region,municipality,scheduled_service,icao_code,iata_code,gps_code,local_code,home_link,wikipedia_link,keywords
0,9/1/2025 12:00:00 AM,AA,1.0,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,...,None,None,None,None,None,None,None,None,None,None
1,9/1/2025 12:00:00 AM,AA,10.0,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,...,None,None,None,None,None,None,None,None,None,None
2,9/1/2025 12:00:00 AM,AA,1002.0,MSN,"Madison, WI",WI,Wisconsin,CLT,"Charlotte, NC",NC,...,None,None,None,None,None,None,None,None,None,None
3,9/1/2025 12:00:00 AM,AA,1003.0,CLT,"Charlotte, NC",NC,North Carolina,MCI,"Kansas City, MO",MO,...,None,None,None,None,None,None,None,None,None,None
4,9/1/2025 12:00:00 AM,AA,1003.0,MCI,"Kansas City, MO",MO,Missouri,CLT,"Charlotte, NC",NC,...,None,None,None,None,None,None,None,None,None,None

## Feature Engineering

### 1.  Parse FL_DATE into year, month, day of month, and day of week

In [22]:
df["FL_DATE"] = pd.to_datetime(df["FL_DATE"], format="%m/%d/%Y %I:%M:%S %p")

In [23]:
df["YEAR"] = df["FL_DATE"].dt.year

In [24]:
df["MONTH"] = df["FL_DATE"].dt.month

In [25]:
df["DAY_OF_MONTH"] = df["FL_DATE"].dt.day

In [26]:
df["DAY_OF_WEEK"] = df["FL_DATE"].dt.dayofweek

In [27]:
df[["DAY_OF_WEEK", "MONTH", "DAY_OF_MONTH", "YEAR"]]

         DAY_OF_WEEK  MONTH  DAY_OF_MONTH  YEAR
0                  0      9             1  2025
1                  0      9             1  2025
2                  0      9             1  2025
3                  0      9             1  2025
4                  0      9             1  2025
...              ...    ...           ...   ...
9356290            0      6            30  2025
9356291            0      6            30  2025
9356292            0      6            30  2025
9356293            0      6            30  2025
9356294            0      6            30  2025

[9082563 rows x 4 columns]

### 2. Add Weather Data

##### 1. Load and Prepare airports.csv

In [28]:
df = df[df['ORIGIN'].notna()]

In [29]:
df['ORIGIN'].unique(), len(df['ORIGIN'].unique())

(array(['JFK', 'LAX', 'MSN', 'CLT', 'MCI', 'BOS', 'DFW', 'HSV', 'ATL',
        'SAV', 'TUS', 'DCA', 'PHX', 'SJC', 'HNL', 'DTW', 'SMF', 'LGA',
        'MIA', 'AUS', 'ABQ', 'PIT', 'CID', 'CHS', 'OMA', 'IAH', 'JAC',
        'ALB', 'LAS', 'ROC', 'JAX', 'RIC', 'BNA', 'LBB', 'ORD', 'MEM',
        'BFL', 'RDU', 'TUL', 'AVL', 'PHL', 'MFE', 'SFO', 'TPA', 'BOI',
        'EWR', 'SAT', 'MRY', 'MCO', 'OGG', 'BWI', 'SJU', 'ONT', 'BUF',
        'BUR', 'SLC', 'PBI', 'GSP', 'CLE', 'CMH', 'RSW', 'DEN', 'IND',
        'STL', 'BDL', 'ORF', 'SNA', 'FLL', 'GRR', 'FCA', 'PNS', 'RNO',
        'ELP', 'PDX', 'GEG', 'STT', 'MSP', 'BGR', 'MYR', 'SRQ', 'MSY',
        'SEA', 'CVG', 'BZN', 'PWM', 'COS', 'SBP', 'PVD', 'ILM', 'SYR',
        'SAN', 'OKC', 'DSM', 'XNA', 'GSO', 'FAT', 'STX', 'MKE', 'SDF',
        'EYW', 'IAD', 'PSP', 'VPS', 'EGE', 'SBA', 'TVC', 'MTJ', 'TYS',
        'MDT', 'LIH', 'BTV', 'STS', 'FSD', 'LIT', 'EUG', 'ANC', 'RDM',
        'KOA', 'MSO', 'KTN', 'FAI', 'OAK', 'OTZ', 'AKN', 'OME', 'JNU',
        'DLG', 'ADQ', 'BET', 'BRW', 'SCC', 'SIT', 'CDV', 'YAK', 'PSG',
        'WRG', 'PSC', 'HPN', 'MHT', 'ACK', 'MVY', 'HYA', 'PQI', 'BQN',
        'ORH', 'ISP', 'PSE', 'MDW', 'BTR', 'DAL', 'BIL', 'AGS', 'HOU',
        'JAN', 'TLH', 'ECP', 'BHM', 'ATW', 'SGF', 'CAE', 'ICT', 'MOB',
        'GPT', 'GNV', 'DAB', 'LEX', 'FAR', 'IDA', 'CHA', 'GRB', 'DAY',
        'ROA', 'MLB', 'LGB', 'BIS', 'TRI', 'TTN', 'PAE', 'PIE', 'BLV',
        'RFD', 'SBN', 'FNT', 'SFB', 'ELM', 'PBG', 'IAG', 'MFR', 'PVU',
        'AZA', 'SCK', 'USA', 'ABE', 'SWF', 'PGD', 'RAP', 'PIA', 'BMI',
        'CAK', 'BLI', 'HGR', 'LCK', 'GUF', 'EVV', 'HTS', 'GTF', 'MOT',
        'SHV', 'PSM', 'FWA', 'ITO', 'PPG', 'HRL', 'MAF', 'BRO', 'MGM',
        'LRD', 'AMA', 'ACT', 'AVP', 'ABI', 'GCK', 'COU', 'CRP', 'CMI',
        'LFT', 'CWA', 'CLL', 'FSM', 'MLU', 'LSE', 'MLI', 'AZO', 'GGG',
        'LAN', 'SPI', 'TXK', 'MQT', 'GJT', 'RST', 'TYR', 'LCH', 'CLD',
        'HHH', 'GRK', 'FAY', 'YUM', 'ALO', 'ACY', 'LBE', 'CRW', 'OAJ',
        'EWN', 'LAW', 'RDD', 'LWS', 'SUN', 'TWF', 'GFK', 'DLH', 'PIH',
        'MBS', 'HLN', 'ABY', 'ASE', 'BGM', 'HIB', 'CIU', 'SGU', 'ABR',
        'ESC', 'INL', 'WYS', 'APN', 'XWA', 'BRD', 'BJI', 'IMT', 'RHI',
        'ATY', 'CDC', 'EKO', 'BTM', 'PLN', 'DRO', 'LNK', 'ACV', 'CPR',
        'GUC', 'GTR', 'GRI', 'SAF', 'MHK', 'SPS', 'SWO', 'SJT', 'FLG',
        'AEX', 'ROW', 'BPT', 'JMS', 'CMX', 'JLN', 'CYS', 'MGW', 'DEC',
        'JST', 'LAR', 'COD', 'SHR', 'DVL', 'LAF', 'FMN', 'SLN', 'PIB',
        'RIW', 'DDC', 'MEI', 'HYS', 'PRC', 'BFF', 'PIR', 'GCC', 'EAR',
        'LBF', 'RKS', 'DIK', 'FOD', 'SUX', 'MCW', 'LBL', 'EAU', 'CHO',
        'BIH', 'HOB', 'SCE', 'HDN', 'OTH', 'GUM', 'SPN', 'ADK', 'CKB',
        'TOL', 'SMX', 'VCT', 'STC', 'VRB', 'SHD', 'LWB', 'PAH', 'ERI',
        'PHF', 'LYH', 'ITH', 'DHN', 'BQK', 'GST'], dtype=object),
 357)

In [30]:
airports = pd.read_csv('../data/airports.csv')
airports = airports.dropna(subset=['iata_code'])
airport_data = airports[['iata_code', 'latitude_deg', 'longitude_deg']]
airport_data = airport_data[airport_data['iata_code'].isin(df['ORIGIN'].unique())]

##### 2. Call Open-Meteo API for Each Airport

In [31]:
import requests
import time

In [32]:
airport_data[airport_data['iata_code'] == 'AUS']

      iata_code  latitude_deg  longitude_deg
38636       AUS     30.197535     -97.662015

In [33]:
url = f"https://archive-api.open-meteo.com/v1/archive?latitude=30.1941&longitude=-97.662015&start_date=2025-01-01&end_date=2026-04-30&hourly=precipitation,wind_speed_10m,snowfall,temperature_2m"
response = requests.get(url).json()
print(f"Response: {response}")

Response: {'latitude': 30.193321, 'longitude': -97.684204, 'generationtime_ms': 5225.386619567871, 'utc_offset_seconds': 0, 'timezone': 'GMT', 'timezone_abbreviation': 'GMT', 'elevation': 147.0, 'hourly_units': {'time': 'iso8601', 'precipitation': 'mm', 'wind_speed_10m': 'km/h', 'snowfall': 'cm', 'temperature_2m': '°C'}, 'hourly': {'time': ['2025-01-01T00:00', '2025-01-01T01:00', '2025-01-01T02:00', '2025-01-01T03:00', '2025-01-01T04:00', '2025-01-01T05:00', '2025-01-01T06:00', '2025-01-01T07:00', '2025-01-01T08:00', '2025-01-01T09:00', '2025-01-01T10:00', '2025-01-01T11:00', '2025-01-01T12:00', '2025-01-01T13:00', '2025-01-01T14:00', '2025-01-01T15:00', '2025-01-01T16:00', '2025-01-01T17:00', '2025-01-01T18:00', '2025-01-01T19:00', '2025-01-01T20:00', '2025-01-01T21:00', '2025-01-01T22:00', '2025-01-01T23:00', '2025-01-02T00:00', '2025-01-02T01:00', '2025-01-02T02:00', '2025-01-02T03:00', '2025-01-02T04:00', '2025-01-02T05:00', '2025-01-02T06:00', '2025-01-02T07:00', '2025-01-02T08:00', '2025-01-02T09:00', '2025-01-02T10:00', '2025-01-02T11:00', '2025-01-02T12:00', '2025-01-02T13:00', '2025-01-02T14:00', '2025-01-02T15:00', '2025-01-02T16:00', '2025-01-02T17:00', '2025-01-02T18:00', '2025-01-02T19:00', '2025-01-02T20:00', '2025-01-02T21:00', '2025-01-02T22:00', '2025-01-02T23:00', '2025-01-03T00:00', '2025-01-03T01:00', '2025-01-03T02:00', '2025-01-03T03:00', '2025-01-03T04:00', '2025-01-03T05:00', '2025-01-03T06:00', '2025-01-03T07:00', '2025-01-03T08:00', '2025-01-03T09:00', '2025-01-03T10:00', '2025-01-03T11:00', '2025-01-03T12:00', '2025-01-03T13:00', '2025-01-03T14:00', '2025-01-03T15:00', '2025-01-03T16:00', '2025-01-03T17:00', '2025-01-03T18:00', '2025-01-03T19:00', '2025-01-03T20:00', '2025-01-03T21:00', '2025-01-03T22:00', '2025-01-03T23:00', '2025-01-04T00:00', '2025-01-04T01:00', '2025-01-04T02:00', '2025-01-04T03:00', '2025-01-04T04:00', '2025-01-04T05:00', '2025-01-04T06:00', '2025-01-04T07:00', '2025-01-04T08:00', '2025-01-04T09:00', '2025-01-04T10:00', '2025-01-04T11:00', '2025-01-04T12:00', '2025-01-04T13:00', '2025-01-04T14:00', '2025-01-04T15:00', '2025-01-04T16:00', '2025-01-04T17:00', '2025-01-04T18:00', '2025-01-04T19:00', '2025-01-04T20:00', '2025-01-04T21:00', '2025-01-04T22:00', '2025-01-04T23:00', '2025-01-05T00:00', '2025-01-05T01:00', '2025-01-05T02:00', '2025-01-05T03:00', '2025-01-05T04:00', '2025-01-05T05:00', '2025-01-05T06:00', '2025-01-05T07:00', '2025-01-05T08:00', '2025-01-05T09:00', '2025-01-05T10:00', '2025-01-05T11:00', '2025-01-05T12:00', '2025-01-05T13:00', '2025-01-05T14:00', '2025-01-05T15:00', '2025-01-05T16:00', '2025-01-05T17:00', '2025-01-05T18:00', '2025-01-05T19:00', '2025-01-05T20:00', '2025-01-05T21:00', '2025-01-05T22:00', '2025-01-05T23:00', '2025-01-06T00:00', '2025-01-06T01:00', '2025-01-06T02:00', '2025-01-06T03:00', '2025-01-06T04:00', '2025-01-06T05:00', '2025-01-06T06:00', '2025-01-06T07:00', '2025-01-06T08:00', '2025-01-06T09:00', '2025-01-06T10:00', '2025-01-06T11:00', '2025-01-06T12:00', '2025-01-06T13:00', '2025-01-06T14:00', '2025-01-06T15:00', '2025-01-06T16:00', '2025-01-06T17:00', '2025-01-06T18:00', '2025-01-06T19:00', '2025-01-06T20:00', '2025-01-06T21:00', '2025-01-06T22:00', '2025-01-06T23:00', '2025-01-07T00:00', '2025-01-07T01:00', '2025-01-07T02:00', '2025-01-07T03:00', '2025-01-07T04:00', '2025-01-07T05:00', '2025-01-07T06:00', '2025-01-07T07:00', '2025-01-07T08:00', '2025-01-07T09:00', '2025-01-07T10:00', '2025-01-07T11:00', '2025-01-07T12:00', '2025-01-07T13:00', '2025-01-07T14:00', '2025-01-07T15:00', '2025-01-07T16:00', '2025-01-07T17:00', '2025-01-07T18:00', '2025-01-07T19:00', '2025-01-07T20:00', '2025-01-07T21:00', '2025-01-07T22:00', '2025-01-07T23:00', '2025-01-08T00:00', '2025-01-08T01:00', '2025-01-08T02:00', '2025-01-08T03:00', '2025-01-08T04:00', '2025-01-08T05:00', '2025-01-08T06:00', '2025-01-08T07:00', '2025-01-08T08:00', '2025-01-08T09:00', '2025-01-08T10:00', '2025-01-08T11:00', '2025-01-08T12:00', '2025-01-08T13:00', '2025-01-08T14:00', '2025-01-08T15:00', '2025-01-08T16:00', '2025-01-08T17:00', '2025-01-08T18:00', '2025-01-08T19:00', '2025-01-08T20:00', '2025-01-08T21:00', '2025-01-08T22:00', '2025-01-08T23:00', '2025-01-09T00:00', '2025-01-09T01:00', '2025-01-09T02:00', '2025-01-09T03:00', '2025-01-09T04:00', '2025-01-09T05:00', '2025-01-09T06:00', '2025-01-09T07:00', '2025-01-09T08:00', '2025-01-09T09:00', '2025-01-09T10:00', '2025-01-09T11:00', '2025-01-09T12:00', '2025-01-09T13:00', '2025-01-09T14:00', '2025-01-09T15:00', '2025-01-09T16:00', '2025-01-09T17:00', '2025-01-09T18:00', '2025-01-09T19:00', '2025-01-09T20:00', '2025-01-09T21:00', '2025-01-09T22:00', '2025-01-09T23:00', '2025-01-10T00:00', '2025-01-10T01:00', '2025-01-10T02:00', '2025-01-10T03:00', '2025-01-10T04:00', '2025-01-10T05:00', '2025-01-10T06:00', '2025-01-10T07:00', '2025-01-10T08:00', '2025-01-10T09:00', '2025-01-10T10:00', '2025-01-10T11:00', '2025-01-10T12:00', '2025-01-10T13:00', '2025-01-10T14:00', '2025-01-10T15:00', '2025-01-10T16:00', '2025-01-10T17:00', '2025-01-10T18:00', '2025-01-10T19:00', '2025-01-10T20:00', '2025-01-10T21:00', '2025-01-10T22:00', '2025-01-10T23:00', '2025-01-11T00:00', '2025-01-11T01:00', '2025-01-11T02:00', '2025-01-11T03:00', '2025-01-11T04:00', '2025-01-11T05:00', '2025-01-11T06:00', '2025-01-11T07:00', '2025-01-11T08:00', '2025-01-11T09:00', '2025-01-11T10:00', '2025-01-11T11:00', '2025-01-11T12:00', '2025-01-11T13:00', '2025-01-11T14:00', '2025-01-11T15:00', '2025-01-11T16:00', '2025-01-11T17:00', '2025-01-11T18:00', '2025-01-11T19:00', '2025-01-11T20:00', '2025-01-11T21:00', '2025-01-11T22:00', '2025-01-11T23:00', '2025-01-12T00:00', '2025-01-12T01:00', '2025-01-12T02:00', '2025-01-12T03:00', '2025-01-12T04:00', '2025-01-12T05:00', '2025-01-12T06:00', '2025-01-12T07:00', '2025-01-12T08:00', '2025-01-12T09:00', '2025-01-12T10:00', '2025-01-12T11:00', '2025-01-12T12:00', '2025-01-12T13:00', '2025-01-12T14:00', '2025-01-12T15:00', '2025-01-12T16:00', '2025-01-12T17:00', '2025-01-12T18:00', '2025-01-12T19:00', '2025-01-12T20:00', '2025-01-12T21:00', '2025-01-12T22:00', '2025-01-12T23:00', '2025-01-13T00:00', '2025-01-13T01:00', '2025-01-13T02:00', '2025-01-13T03:00', '2025-01-13T04:00', '2025-01-13T05:00', '2025-01-13T06:00', '2025-01-13T07:00', '2025-01-13T08:00', '2025-01-13T09:00', '2025-01-13T10:00', '2025-01-13T11:00', '2025-01-13T12:00', '2025-01-13T13:00', '2025-01-13T14:00', '2025-01-13T15:00', '2025-01-13T16:00', '2025-01-13T17:00', '2025-01-13T18:00', '2025-01-13T19:00', '2025-01-13T20:00', '2025-01-13T21:00', '2025-01-13T22:00', '2025-01-13T23:00', '2025-01-14T00:00', '2025-01-14T01:00', '2025-01-14T02:00', '2025-01-14T03:00', '2025-01-14T04:00', '2025-01-14T05:00', '2025-01-14T06:00', '2025-01-14T07:00', '2025-01-14T08:00', '2025-01-14T09:00', '2025-01-14T10:00', '2025-01-14T11:00', '2025-01-14T12:00', '2025-01-14T13:00', '2025-01-14T14:00', '2025-01-14T15:00', '2025-01-14T16:00', '2025-01-14T17:00', '2025-01-14T18:00', '2025-01-14T19:00', '2025-01-14T20:00', '2025-01-14T21:00', '2025-01-14T22:00', '2025-01-14T23:00', '2025-01-15T00:00', '2025-01-15T01:00', '2025-01-15T02:00', '2025-01-15T03:00', '2025-01-15T04:00', '2025-01-15T05:00', '2025-01-15T06:00', '2025-01-15T07:00', '2025-01-15T08:00', '2025-01-15T09:00', '2025-01-15T10:00', '2025-01-15T11:00', '2025-01-15T12:00', '2025-01-15T13:00', '2025-01-15T14:00', '2025-01-15T15:00', '2025-01-15T16:00', '2025-01-15T17:00', '2025-01-15T18:00', '2025-01-15T19:00', '2025-01-15T20:00', '2025-01-15T21:00', '2025-01-15T22:00', '2025-01-15T23:00', '2025-01-16T00:00', '2025-01-16T01:00', '2025-01-16T02:00', '2025-01-16T03:00', '2025-01-16T04:00', '2025-01-16T05:00', '2025-01-16T06:00', '2025-01-16T07:00', '2025-01-16T08:00', '2025-01-16T09:00', '2025-01-16T10:00', '2025-01-16T11:00', '2025-01-16T12:00', '2025-01-16T13:00', '2025-01-16T14:00', '2025-01-16T15:00', '2025-01-16T16:00', '2025-01-16T17:00', '2025-01-16T18:00', '2025-01-16T19:00', '2025-01-16T20:00', '2025-01-16T21:00', '2025-01-16T22:00', '2025-01-16T23:00', '2025-01-17T00:00', '2025-01-17T01:00', '2025-01-17T02:00', '2025-01-17T03:00', '2025-01-17T04:00', '2025-01-17T05:00', '2025-01-17T06:00', '2025-01-17T07:00', '2025-01-17T08:00', '2025-01-17T09:00', '2025-01-17T10:00', '2025-01-17T11:00', '2025-01-17T12:00', '2025-01-17T13:00', '2025-01-17T14:00', '2025-01-17T15:00', '2025-01-17T16:00', '2025-01-17T17:00', '2025-01-17T18:00', '2025-01-17T19:00', '2025-01-17T20:00', '2025-01-17T21:00', '2025-01-17T22:00', '2025-01-17T23:00', '2025-01-18T00:00', '2025-01-18T01:00', '2025-01-18T02:00', '2025-01-18T03:00', '2025-01-18T04:00', '2025-01-18T05:00', '2025-01-18T06:00', '2025-01-18T07:00', '2025-01-18T08:00', '2025-01-18T09:00', '2025-01-18T10:00', '2025-01-18T11:00', '2025-01-18T12:00', '2025-01-18T13:00', '2025-01-18T14:00', '2025-01-18T15:00', '2025-01-18T16:00', '2025-01-18T17:00', '2025-01-18T18:00', '2025-01-18T19:00', '2025-01-18T20:00', '2025-01-18T21:00', '2025-01-18T22:00', '2025-01-18T23:00', '2025-01-19T00:00', '2025-01-19T01:00', '2025-01-19T02:00', '2025-01-19T03:00', '2025-01-19T04:00', '2025-01-19T05:00', '2025-01-19T06:00', '2025-01-19T07:00', '2025-01-19T08:00', '2025-01-19T09:00', '2025-01-19T10:00', '2025-01-19T11:00', '2025-01-19T12:00', '2025-01-19T13:00', '2025-01-19T14:00', '2025-01-19T15:00', '2025-01-19T16:00', '2025-01-19T17:00', '2025-01-19T18:00', '2025-01-19T19:00', '2025-01-19T20:00', '2025-01-19T21:00', '2025-01-19T22:00', '2025-01-19T23:00', '2025-01-20T00:00', '2025-01-20T01:00', '2025-01-20T02:00', '2025-01-20T03:00', '2025-01-20T04:00', '2025-01-20T05:00', '2025-01-20T06:00', '2025-01-20T07:00', '2025-01-20T08:00', '2025-01-20T09:00', '2025-01-20T10:00', '2025-01-20T11:00', '2025-01-20T12:00', '2025-01-20T13:00', '2025-01-20T14:00', '2025-01-20T15:00', '2025-01-20T16:00', '2025-01-20T17:00', '2025-01-20T18:00', '2025-01-20T19:00', '2025-01-20T20:00', '2025-01-20T21:00', '2025-01-20T22:00', '2025-01-20T23:00', '2025-01-21T00:00', '2025-01-21T01:00', '2025-01-21T02:00', '2025-01-21T03:00', '2025-01-21T04:00', '2025-01-21T05:00', '2025-01-21T06:00', '2025-01-21T07:00', '2025-01-21T08:00', '2025-01-21T09:00', '2025-01-21T10:00', '2025-01-21T11:00', '2025-01-21T12:00', '2025-01-21T13:00', '2025-01-21T14:00', '2025-01-21T15:00', '2025-01-21T16:00', '2025-01-21T17:00', '2025-01-21T18:00', '2025-01-21T19:00', '2025-01-21T20:00', '2025-01-21T21:00', '2025-01-21T22:00', '2025-01-21T23:00', '2025-01-22T00:00', '2025-01-22T01:00', '2025-01-22T02:00', '2025-01-22T03:00', '2025-01-22T04:00', '2025-01-22T05:00', '2025-01-22T06:00', '2025-01-22T07:00', '2025-01-22T08:00', '2025-01-22T09:00', '2025-01-22T10:00', '2025-01-22T11:00', '2025-01-22T12:00', '2025-01-22T13:00', '2025-01-22T14:00', '2025-01-22T15:00', '2025-01-22T16:00', '2025-01-22T17:00', '2025-01-22T18:00', '2025-01-22T19:00', '2025-01-22T20:00', '2025-01-22T21:00', '2025-01-22T22:00', '2025-01-22T23:00', '2025-01-23T00:00', '2025-01-23T01:00', '2025-01-23T02:00', '2025-01-23T03:00', '2025-01-23T04:00', '2025-01-23T05:00', '2025-01-23T06:00', '2025-01-23T07:00', '2025-01-23T08:00', '2025-01-23T09:00', '2025-01-23T10:00', '2025-01-23T11:00', '2025-01-23T12:00', '2025-01-23T13:00', '2025-01-23T14:00', '2025-01-23T15:00', '2025-01-23T16:00', '2025-01-23T17:00', '2025-01-23T18:00', '2025-01-23T19:00', '2025-01-23T20:00', '2025-01-23T21:00', '2025-01-23T22:00', '2025-01-23T23:00', '2025-01-24T00:00', '2025-01-24T01:00', '2025-01-24T02:00', '2025-01-24T03:00', '2025-01-24T04:00', '2025-01-24T05:00', '2025-01-24T06:00', '2025-01-24T07:00', '2025-01-24T08:00', '2025-01-24T09:00', '2025-01-24T10:00', '2025-01-24T11:00', '2025-01-24T12:00', '2025-01-24T13:00', '2025-01-24T14:00', '2025-01-24T15:00', '2025-01-24T16:00', '2025-01-24T17:00', '2025-01-24T18:00', '2025-01-24T19:00', '2025-01-24T20:00', '2025-01-24T21:00', '2025-01-24T22:00', '2025-01-24T23:00', '2025-01-25T00:00', '2025-01-25T01:00', '2025-01-25T02:00', '2025-01-25T03:00', '2025-01-25T04:00', '2025-01-25T05:00', '2025-01-25T06:00', '2025-01-25T07:00', '2025-01-25T08:00', '2025-01-25T09:00', '2025-01-25T10:00', '2025-01-25T11:00', '2025-01-25T12:00', '2025-01-25T13:00', '2025-01-25T14:00', '2025-01-25T15:00', '2025-01-25T16:00', '2025-01-25T17:00', '2025-01-25T18:00', '2025-01-25T19:00', '2025-01-25T20:00', '2025-01-25T21:00', '2025-01-25T22:00', '2025-01-25T23:00', '2025-01-26T00:00', '2025-01-26T01:00', '2025-01-26T02:00', '2025-01-26T03:00', '2025-01-26T04:00', '2025-01-26T05:00', '2025-01-26T06:00', '2025-01-26T07:00', '2025-01-26T08:00', '2025-01-26T09:00', '2025-01-26T10:00', '2025-01-26T11:00', '2025-01-26T12:00', '2025-01-26T13:00', '2025-01-26T14:00', '2025-01-26T15:00', '2025-01-26T16:00', '2025-01-26T17:00', '2025-01-26T18:00', '2025-01-26T19:00', '2025-01-26T20:00', '2025-01-26T21:00', '2025-01-26T22:00', '2025-01-26T23:00', '2025-01-27T00:00', '2025-01-27T01:00', '2025-01-27T02:00', '2025-01-27T03:00', '2025-01-27T04:00', '2025-01-27T05:00', '2025-01-27T06:00', '2025-01-27T07:00', '2025-01-27T08:00', '2025-01-27T09:00', '2025-01-27T10:00', '2025-01-27T11:00', '2025-01-27T12:00', '2025-01-27T13:00', '2025-01-27T14:00', '2025-01-27T15:00', '2025-01-27T16:00', '2025-01-27T17:00', '2025-01-27T18:00', '2025-01-27T19:00', '2025-01-27T20:00', '2025-01-27T21:00', '2025-01-27T22:00', '2025-01-27T23:00', '2025-01-28T00:00', '2025-01-28T01:00', '2025-01-28T02:00', '2025-01-28T03:00', '2025-01-28T04:00', '2025-01-28T05:00', '2025-01-28T06:00', '2025-01-28T07:00', '2025-01-28T08:00', '2025-01-28T09:00', '2025-01-28T10:00', '2025-01-28T11:00', '2025-01-28T12:00', '2025-01-28T13:00', '2025-01-28T14:00', '2025-01-28T15:00', '2025-01-28T16:00', '2025-01-28T17:00', '2025-01-28T18:00', '2025-01-28T19:00', '2025-01-28T20:00', '2025-01-28T21:00', '2025-01-28T22:00', '2025-01-28T23:00', '2025-01-29T00:00', '2025-01-29T01:00', '2025-01-29T02:00', '2025-01-29T03:00', '2025-01-29T04:00', '2025-01-29T05:00', '2025-01-29T06:00', '2025-01-29T07:00', '2025-01-29T08:00', '2025-01-29T09:00', '2025-01-29T10:00', '2025-01-29T11:00', '2025-01-29T12:00', '2025-01-29T13:00', '2025-01-29T14:00', '2025-01-29T15:00', '2025-01-29T16:00', '2025-01-29T17:00', '2025-01-29T18:00', '2025-01-29T19:00', '2025-01-29T20:00', '2025-01-29T21:00', '2025-01-29T22:00', '2025-01-29T23:00', '2025-01-30T00:00', '2025-01-30T01:00', '2025-01-30T02:00', '2025-01-30T03:00', '2025-01-30T04:00', '2025-01-30T05:00', '2025-01-30T06:00', '2025-01-30T07:00', '2025-01-30T08:00', '2025-01-30T09:00', '2025-01-30T10:00', '2025-01-30T11:00', '2025-01-30T12:00', '2025-01-30T13:00', '2025-01-30T14:00', '2025-01-30T15:00', '2025-01-30T16:00', '2025-01-30T17:00', '2025-01-30T18:00', '2025-01-30T19:00', '2025-01-30T20:00', '2025-01-30T21:00', '2025-01-30T22:00', '2025-01-30T23:00', '2025-01-31T00:00', '2025-01-31T01:00', '2025-01-31T02:00', '2025-01-31T03:00', '2025-01-31T04:00', '2025-01-31T05:00', '2025-01-31T06:00', '2025-01-31T07:00', '2025-01-31T08:00', '2025-01-31T09:00', '2025-01-31T10:00', '2025-01-31T11:00', '2025-01-31T12:00', '2025-01-31T13:00', '2025-01-31T14:00', '2025-01-31T15:00', '2025-01-31T16:00', '2025-01-31T17:00', '2025-01-31T18:00', '2025-01-31T19:00', '2025-01-31T20:00', '2025-01-31T21:00', '2025-01-31T22:00', '2025-01-31T23:00', '2025-02-01T00:00', '2025-02-01T01:00', '2025-02-01T02:00', '2025-02-01T03:00', '2025-02-01T04:00', '2025-02-01T05:00', '2025-02-01T06:00', '2025-02-01T07:00', '2025-02-01T08:00', '2025-02-01T09:00', '2025-02-01T10:00', '2025-02-01T11:00', '2025-02-01T12:00', '2025-02-01T13:00', '2025-02-01T14:00', '2025-02-01T15:00', '2025-02-01T16:00', '2025-02-01T17:00', '2025-02-01T18:00', '2025-02-01T19:00', '2025-02-01T20:00', '2025-02-01T21:00', '2025-02-01T22:00', '2025-02-01T23:00', '2025-02-02T00:00', '2025-02-02T01:00', '2025-02-02T02:00', '2025-02-02T03:00', '2025-02-02T04:00', '2025-02-02T05:00', '2025-02-02T06:00', '2025-02-02T07:00', '2025-02-02T08:00', '2025-02-02T09:00', '2025-02-02T10:00', '2025-02-02T11:00', '2025-02-02T12:00', '2025-02-02T13:00', '2025-02-02T14:00', '2025-02-02T15:00', '2025-02-02T16:00', '2025-02-02T17:00', '2025-02-02T18:00', '2025-02-02T19:00', '2025-02-02T20:00', '2025-02-02T21:00', '2025-02-02T22:00', '2025-02-02T23:00', '2025-02-03T00:00', '2025-02-03T01:00', '2025-02-03T02:00', '2025-02-03T03:00', '2025-02-03T04:00', '2025-02-03T05:00', '2025-02-03T06:00', '2025-02-03T07:00', '2025-02-03T08:00', '2025-02-03T09:00', '2025-02-03T10:00', '2025-02-03T11:00', '2025-02-03T12:00', '2025-02-03T13:00', '2025-02-03T14:00', '2025-02-03T15:00', '2025-02-03T16:00', '2025-02-03T17:00', '2025-02-03T18:00', '2025-02-03T19:00', '2025-02-03T20:00', '2025-02-03T21:00', '2025-02-03T22:00', '2025-02-03T23:00', '2025-02-04T00:00', '2025-02-04T01:00', '2025-02-04T02:00', '2025-02-04T03:00', '2025-02-04T04:00', '2025-02-04T05:00', '2025-02-04T06:00', '2025-02-04T07:00', '2025-02-04T08:00', '2025-02-04T09:00', '2025-02-04T10:00', '2025-02-04T11:00', '2025-02-04T12:00', '2025-02-04T13:00', '2025-02-04T14:00', '2025-02-04T15:00', '2025-02-04T16:00', '2025-02-04T17:00', '2025-02-04T18:00', '2025-02-04T19:00', '2025-02-04T20:00', '2025-02-04T21:00', '2025-02-04T22:00', '2025-02-04T23:00', '2025-02-05T00:00', '2025-02-05T01:00', '2025-02-05T02:00', '2025-02-05T03:00', '2025-02-05T04:00', '2025-02-05T05:00', '2025-02-05T06:00', '2025-02-05T07:00', '2025-02-05T08:00', '2025-02-05T09:00', '2025-02-05T10:00', '2025-02-05T11:00', '2025-02-05T12:00', '2025-02-05T13:00', '2025-02-05T14:00', '2025-02-05T15:00', '2025-02-05T16:00', '2025-02-05T17:00', '2025-02-05T18:00', '2025-02-05T19:00', '2025-02-05T20:00', '2025-02-05T21:00', '2025-02-05T22:00', '2025-02-05T23:00', '2025-02-06T00:00', '2025-02-06T01:00', '2025-02-06T02:00', '2025-02-06T03:00', '2025-02-06T04:00', '2025-02-06T05:00', '2025-02-06T06:00', '2025-02-06T07:00', '2025-02-06T08:00', '2025-02-06T09:00', '2025-02-06T10:00', '2025-02-06T11:00', '2025-02-06T12:00', '2025-02-06T13:00', '2025-02-06T14:00', '2025-02-06T15:00', '2025-02-06T16:00', '2025-02-06T17:00', '2025-02-06T18:00', '2025-02-06T19:00', '2025-02-06T20:00', '2025-02-06T21:00', '2025-02-06T22:00', '2025-02-06T23:00', '2025-02-07T00:00', '2025-02-07T01:00', '2025-02-07T02:00', '2025-02-07T03:00', '2025-02-07T04:00', '2025-02-07T05:00', '2025-02-07T06:00', '2025-02-07T07:00', '2025-02-07T08:00', '2025-02-07T09:00', '2025-02-07T10:00', '2025-02-07T11:00', '2025-02-07T12:00', '2025-02-07T13:00', '2025-02-07T14:00', '2025-02-07T15:00', '2025-02-07T16:00', '2025-02-07T17:00', '2025-02-07T18:00', '2025-02-07T19:00', '2025-02-07T20:00', '2025-02-07T21:00', '2025-02-07T22:00', '2025-02-07T23:00', '2025-02-08T00:00', '2025-02-08T01:00', '2025-02-08T02:00', '2025-02-08T03:00', '2025-02-08T04:00', '2025-02-08T05:00', '2025-02-08T06:00', '2025-02-08T07:00', '2025-02-08T08:00', '2025-02-08T09:00', '2025-02-08T10:00', '2025-02-08T11:00', '2025-02-08T12:00', '2025-02-08T13:00', '2025-02-08T14:00', '2025-02-08T15:00', '2025-02-08T16:00', '2025-02-08T17:00', '2025-02-08T18:00', '2025-02-08T19:00', '2025-02-08T20:00', '2025-02-08T21:00', '2025-02-08T22:00', '2025-02-08T23:00', '2025-02-09T00:00', '2025-02-09T01:00', '2025-02-09T02:00', '2025-02-09T03:00', '2025-02-09T04:00', '2025-02-09T05:00', '2025-02-09T06:00', '2025-02-09T07:00', '2025-02-09T08:00', '2025-02-09T09:00', '2025-02-09T10:00', '2025-02-09T11:00', '2025-02-09T12:00', '2025-02-09T13:00', '2025-02-09T14:00', '2025-02-09T15:00', '2025-02-09T16:00', '2025-02-09T17:00', '2025-02-09T18:00', '2025-02-09T19:00', '2025-02-09T20:00', '2025-02-09T21:00', '2025-02-09T22:00', '2025-02-09T23:00', '2025-02-10T00:00', '2025-02-10T01:00', '2025-02-10T02:00', '2025-02-10T03:00', '2025-02-10T04:00', '2025-02-10T05:00', '2025-02-10T06:00', '2025-02-10T07:00', '2025-02-10T08:00', '2025-02-10T09:00', '2025-02-10T10:00', '2025-02-10T11:00', '2025-02-10T12:00', '2025-02-10T13:00', '2025-02-10T14:00', '2025-02-10T15:00', '2025-02-10T16:00', '2025-02-10T17:00', '2025-02-10T18:00', '2025-02-10T19:00', '2025-02-10T20:00', '2025-02-10T21:00', '2025-02-10T22:00

In [35]:
weather_data = []

from tqdm import tqdm

for _, row in tqdm(airport_data.iterrows(), total=len(airport_data)):
    url = f"https://archive-api.open-meteo.com/v1/archive?latitude={row['latitude_deg']}&longitude={row['longitude_deg']}&start_date=2025-01-01&end_date=2026-04-30&hourly=precipitation,wind_speed_10m,snowfall,temperature_2m"
    response = requests.get(url, timeout=30).json()
    
    hourly = response['hourly']
    
    response_df = pd.DataFrame({
        'iata_code': row['iata_code'],
        'datetime': hourly['time'],
        'precipitation': hourly['precipitation'],
        'wind_speed': hourly['wind_speed_10m'],
        'snowfall': hourly['snowfall'],
        'temperature': hourly['temperature_2m']
    })
    
    weather_data.append(response_df)
    time.sleep(1)

weather_df = pd.concat(weather_data, ignore_index=True)

100%|██████████| 357/357 [31:28<00:00,  5.29s/it]

In [ ]:
weather_df.head()

,iata_code,datetime,precipitation,wind_speed,snowfall,temperature
0,ABE,2025-01-01T00:00,0.1,14.8,0.0,6.4
1,ABE,2025-01-01T01:00,0.4,14.9,0.0,7.6
2,ABE,2025-01-01T02:00,1.8,14.1,0.0,7.1
3,ABE,2025-01-01T03:00,3.0,8.8,0.0,6.9
4,ABE,2025-01-01T04:00,2.0,5.8,0.0,6.7

In [ ]:
len(airport_data), len(airports)

In [ ]:
airport_data.shape

##### 3. Save Weather Data to Parquet Immediately

In [40]:
weather_df.to_parquet('../data/weather_data.parquet', index=False)

##### 4. Parse Datetime

In [42]:
weather_df['datetime'] = pd.to_datetime(weather_df['datetime'])
weather_df['DATE'] = weather_df['datetime'].dt.date
weather_df['HOUR'] = weather_df['datetime'].dt.hour

##### 5. Prepare Flight Date for Joining

In [43]:
df['DATE'] = df['FL_DATE'].dt.date

In [51]:
df = df.drop(columns=['id', 'ident', 'type', 'name',
       'latitude_deg', 'longitude_deg', 'elevation_ft', 'continent',
       'iso_country', 'iso_region', 'municipality', 'scheduled_service',
       'icao_code', 'iata_code', 'gps_code', 'local_code', 'home_link',
       'wikipedia_link', 'keywords'])

In [53]:
df.columns

Index(['FL_DATE', 'OP_UNIQUE_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN',
       'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR', 'ORIGIN_STATE_NM', 'DEST',
       'DEST_CITY_NAME', 'DEST_STATE_ABR', 'DEST_STATE_NM', 'CRS_DEP_TIME',
       'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'ARR_DELAY', 'ARR_DEL15',
       'CANCELLED', 'DIVERTED', 'CRS_ELAPSED_TIME', 'DISTANCE',
       'DISTANCE_GROUP', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY',
       'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY', 'YEAR', 'MONTH',
       'DAY_OF_MONTH', 'DAY_OF_WEEK', 'DATE'],
      dtype='object')

### 3.  Extract departure hour from CRS_DEP_TIME using integer division by 100

In [55]:
df["DEPARTURE_HOUR"] = df["CRS_DEP_TIME"] // 100
df["DEPARTURE_MINUTE"] = df["CRS_DEP_TIME"] % 100
df = df.drop(columns=["CRS_DEP_TIME"])

In [56]:
# Merge the dataframe with the specified columns from the newly weather dataframe
df = df.merge(
    weather_df[['iata_code', 'DATE', 'HOUR', 'precipitation', 'wind_speed', 'snowfall', 'temperature']],
    left_on=['ORIGIN', 'DATE', 'DEPARTURE_HOUR'],
    right_on=['iata_code', 'DATE', 'HOUR'],
    how='left'
)

In [58]:
weather_cols = ['precipitation', 'wind_speed', 'snowfall', 'temperature']

df[weather_cols] = df[weather_cols].fillna(df[weather_cols].mean())

In [59]:
df = df.drop(columns=['iata_code', 'DATE', 'HOUR'])

### 4.  Create ROUTE feature by combining ORIGIN and DEST

In [60]:
df["ROUTE"] = df["ORIGIN"] + "-" + df["DEST"]
df["ROUTE"].head()

0    JFK-LAX
1    LAX-JFK
2    MSN-CLT
3    CLT-MCI
4    MCI-CLT
Name: ROUTE, dtype: object

### 5.  Create IsHolidayPeriod using your holiday function

In [62]:
def isHolidayPeriod(date):
    # df["MONTH"] = df["FL_DATE"].dt.month
    # df["DAY_OF_MONTH"] = df["FL_DATE"].dt.day
    
    # MLK Day
    if date.month == 1 and 15 <= date.day <= 20:
        return 1

    # Presidents Day
    if date.month == 2 and 13 <= date.day <= 17:
        return 1
    
    # Spring Break
    if (date.month == 3 and date.day >= 15) or (date.month == 4 and date.day <= 15):
        return 1
    
    # Memorial Day 
    if date.month == 5 and 23 <= date.day <= 27:
        return 1
    
    # Fourth of July
    if date.month == 7 and 1 <= date.day <= 7:
        return 1
    
    # Labor Day
    if (date.month == 8 and date.day >= 29) or (date.month == 9 and date.day <= 2):
        return 1
    
    # Thanksgiving (Nov 20 – Dec 1)
    if (date.month == 11 and date.day >= 20) or (date.month == 12 and date.day <= 1):
        return 1

    # Christmas & New Year (Dec 20 – Jan 5)
    if (date.month == 12 and date.day >= 20) or (date.month == 1 and date.day <= 5):
        return 1

    return 0

In [63]:
df['IS_HOLIDAY_PERIOD'] = df['FL_DATE'].apply(isHolidayPeriod)

In [68]:
df['IS_HOLIDAY_PERIOD'].head()

0    1
1    1
2    1
3    1
4    1
Name: IS_HOLIDAY_PERIOD, dtype: int64

### 6.  Create target variable DEP_DELAY from DEP_DEL_15

In [69]:
df['DELAYED'] = (df['DEP_DELAY'] > 15).astype(int)

### 7. Drop DEP_DEL15, ARR_DEL15, ARR_DELAY, CANCELLED, DIVERTED

In [70]:
'DEP_DEL15' in df, 'ARR_DEL15' in df, 'ARR_DELAY' in df, 'CANCELLED' in df, 'DIVERTED' in df

(True, True, True, True, True)

In [71]:
df = df.drop(columns=['DEP_DEL15', 'ARR_DEL15', 'ARR_DELAY', 'CANCELLED', 'DIVERTED'])

### 8.  Label encode OP_UNIQUE_CARRIER, ORIGIN_STATE_ABR, DEST_STATE_ABR

In [72]:
from sklearn.preprocessing import LabelEncoder
import joblib

In [73]:
df[['OP_UNIQUE_CARRIER', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR']].head()

  OP_UNIQUE_CARRIER ORIGIN_STATE_ABR DEST_STATE_ABR
0                AA               NY             CA
1                AA               CA             NY
2                AA               WI             NC
3                AA               NC             MO
4                AA               MO             NC

In [74]:
le_carrier = LabelEncoder()
le_origin_state = LabelEncoder()
le_dest_state = LabelEncoder()

df['OP_UNIQUE_CARRIER'] = le_carrier.fit_transform(df['OP_UNIQUE_CARRIER'])
df['ORIGIN_STATE_ABR'] = le_origin_state.fit_transform(df['ORIGIN_STATE_ABR'])
df['DEST_STATE_ABR'] = le_dest_state.fit_transform(df['DEST_STATE_ABR'])

In [75]:
df[['OP_UNIQUE_CARRIER', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR']].head()

   OP_UNIQUE_CARRIER  ORIGIN_STATE_ABR  DEST_STATE_ABR
0                  0                32               4
1                  0                 4              32
2                  0                49              25
3                  0                25              22
4                  0                22              25

In [76]:
joblib.dump(le_carrier, '../encodings/le_carrier.pkl')
joblib.dump(le_origin_state, '../encodings/le_origin_state.pkl')
joblib.dump(le_dest_state, '../encodings/le_dest_state.pkl')

['../encodings/le_dest_state.pkl']

### 9.  Define features X and target y -- Feature Selection

In [77]:
y = df["DELAYED"]

In [78]:
correlation_matrix = df.corr(numeric_only=True, method='spearman')
correlation_matrix

,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_STATE_ABR,DEST_STATE_ABR,DEP_DELAY,DEP_DELAY_NEW,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,...,DAY_OF_MONTH,DAY_OF_WEEK,DEPARTURE_HOUR,DEPARTURE_MINUTE,precipitation,wind_speed,snowfall,temperature,IS_HOLIDAY_PERIOD,DELAYED
OP_UNIQUE_CARRIER,1.000000,0.269893,-0.026916,-0.026653,0.043496,0.012831,-0.195294,-0.187854,-0.188876,-0.022210,...,-0.000043,-0.003810,-0.007538,-0.009393,-0.021555,-0.019707,0.010583,-0.052994,0.001710,-0.010214
OP_CARRIER_FL_NUM,0.269893,1.000000,0.044098,0.049921,-0.054966,-0.026878,-0.320864,-0.362193,-0.359256,0.002285,...,0.000785,0.000616,0.023033,0.005780,-0.019029,0.014362,0.011377,-0.051094,-0.000546,0.001742
ORIGIN_STATE_ABR,-0.026916,0.044098,1.000000,0.013719,-0.004865,0.000684,-0.007074,-0.033375,-0.040283,0.006570,...,-0.001141,-0.005162,-0.012519,0.001890,0.040681,0.151713,0.013436,-0.069213,-0.007652,0.007333
DEST_STATE_ABR,-0.026653,0.049921,0.013719,1.000000,-0.009168,-0.001313,-0.033183,-0.033370,-0.040284,0.001352,...,-0.001236,-0.005361,0.003029,-0.003760,0.001379,0.031136,-0.005939,0.037024,-0.007632,0.005608
DEP_DELAY,0.043496,-0.054966,-0.004865,-0.009168,1.000000,0.872249,0.054574,0.065691,0.063462,0.469570,...,0.003839,0.040049,0.204811,0.055249,0.088380,0.045663,0.041757,0.075332,0.027275,0.705905
DEP_DELAY_NEW,0.012831,-0.026878,0.000684,-0.001313,0.872249,1.000000,0.036800,0.042451,0.040666,0.537585,...,0.002797,0.034978,0.227731,0.055695,0.093622,0.052776,0.045005,0.077369,0.024281,0.809292
CRS_ELAPSED_TIME,-0.195294,-0.320864,-0.007074,-0.033183,0.054574,0.036800,1.000000,0.979827,0.967207,0.014983,...,-0.000650,0.009399,-0.033747,-0.000238,0.009601,0.011688,-0.000114,-0.000233,0.019037,0.014881
DISTANCE,-0.187854,-0.362193,-0.033375,-0.033370,0.065691,0.042451,0.979827,1.000000,0.986522,0.017856,...,0.000278,0.010396,-0.027044,0.006106,0.006332,-0.008444,-0.010295,0.035833,0.014595,0.015374
DISTANCE_GROUP,-0.188876,-0.359256,-0.040283,-0.040284,0.063462,0.040666,0.967207,0.986522,1.000000,0.017075,...,0.000323,0.010284,-0.026766,0.007138,0.005789,-0.009175,-0.009432,0.035301,0.014529,0.013999
CARRIER_DELAY,-0.022210,0.002285,0.006570,0.001352,0.469570,0.537585,0.014983,0.017856,0.017075,1.000000,...,0.002547,0.025408,0.103780,0.024346,0.050656,0.036195,0.032616,0.036221,0.017184,0.585310
WEATHER_DELAY,-0.021227,0.033823,0.012283,0.014794,0.168949,0.193675,-0.017174,-0.020968,-0.020711,-0.029624,...,0.002545,0.006611,0.037107,0.007209,0.077799,0.022196,0.076162,0.014331,-0.000447,0.205052
NAS_DELAY,-0.021742,-0.007407,0.016644,0.009681,0.327887,0.358382,0.037356,0.032698,0.031088,0.290158,...,-0.007620,0.021762,0.083063,0.020651,0.089310,0.048281,0.090688,0.017900,0.009742,0.347070
SECURITY_DELAY,-0.004950,-0.005926,-0.000829,0.001818,0.035916,0.041176,0.005102,0.005712,0.005504,-0.003522,...,-0.000122,0.003696,0.006701,0.000843,0.003068,0.003302,0.000970,0.003282,0.003828,0.043961
LATE_AIRCRAFT_DELAY,-0.004536,-0.001860,0.007726,0.011242,0.495372,0.567925,-0.006104,-0.001319,-0.003098,0.387193,...,0.000846,0.024798,0.202601,0.049554,0.084502,0.048386,0.031094,0.077220,0.016871,0.635808
YEAR,-0.002345,0.009968,-0.008576,-0.008640,-0.009957,-0.001872,0.023012,0.004471,0.004711,-0.000040,...,-0.014936,0.001261,0.000398,0.000093,-0.000922,0.059737,0.031001,-0.202628,0.162623,-0.002030
MONTH,0.000735,0.004904,0.011711,0.011753,0.025627,0.027475,-0.021772,-0.007424,-0.007623,0.015879,...,0.016091,-0.009205,-0.000674,0.001193,0.000987,-0.092992,-0.067315,0.319242,-0.151349,0.023087
DAY_OF_MONTH,-0.000043,0.000785,-0.001141,-0.001236,0.003839,0.002797,-0.000650,0.000278,0.000323,0.002547,...,1.000000,0.000203,-0.000346,0.000402,-0.009387,-0.003233,-0.016671,0.034344,0.045041,0.001539
DAY_OF_WEEK,-0.003810,0.000616,-0.005162,-0.005361,0.040049,0.034978,0.009399,0.010396,0.010284,0.025408,...,0.000203,1.000000,0.004493,0.000186,0.013835,0.002909,0.012777,0.013736,0.032175,0.028634
DEPARTURE_HOUR,-0.007538,0.023033,-0.012519,0.003029,0.204811,0.227731,-0.033747,-0.027044,-0.026766,0.103780,...,-0.000346,0.004493,1.000000,0.172263,0.085204,0.121863,-0.008824,0.251822,0.003500,0.197426
DEPARTURE_MINUTE,-0.009393,0.005780,0.001890,-0.003760,0.055249,0.055695,-0.000238,0.006106,0.007138,0.024346,...,0.000402,0.000186,0.172263,1.000000,0.014415,0.009182,-0.002906,0.032043,-0.000237,0.045069
precipitation,-0.021555,-0.019029,0.040681,0.001379,0.088380,0.093622,0.009601,0.006332,0.005789,0.050656,...,-0.009387,0.013835,0.085204,0.014415,1.000000,0.150373,0.298420,0.038040,0.012148,0.087191
wind_speed,-0.019707,0.014362,0.151713,0.031136,0.045663,0.052776,0.011688,-0.008444,-0.009175,0.036195,...,-0.003233,0.002909,0.121863,0.009182,0.150373,1.000000,0.055055,-0.033511,0.072912,0.052193
snowfall,0.010583,0.011377,0.013436,-0.005939,0.041757,0.045005,-0.000114,-0.010295,-0.009432,0.032616,...,-0.016671,0.012777,-0.008824,-0.002906,0.298420,0.055055,1.000000,-0.167705,0.024645,0.041985
temperature,-0.052994,-0.051094,-0.069213,0.037024,0.075332,0.077369,-0.000233,0.035833,0.035301,0.036221,...,0.034344,0.013736,0.251822,0.032043,0.038040,-0.033511,-0.167705,1.000000,-0.143379,0.066573
IS_HOLIDAY_PERIOD,0.001710,-0.000546,-0.007652,-0.007632,0.027275,0.024281,0.019037,0.014595,0.014529,0.017184,...,0.045041,0.032175,0.003500,-0.000237,0.012148,0.072912,0.024645,-0.143379,1.000000,0.019809
DELAYED,-0.010214,0.001742,0.007333,0.005608,0.705905,0.809292,0.014881,0.015374,0.013999,0.585310,...,0.001539,0.028634,0.197426,0.045069,0.087191,0.052193,0.041985,0.066573,0.019809,1.000000

In [79]:
numerical_columns = correlation_matrix['DELAYED'].sort_values(ascending=False)

In [80]:
numerical_columns

DELAYED                1.000000
DEP_DELAY_NEW          0.809292
DEP_DELAY              0.705905
LATE_AIRCRAFT_DELAY    0.635808
CARRIER_DELAY          0.585310
NAS_DELAY              0.347070
WEATHER_DELAY          0.205052
DEPARTURE_HOUR         0.197426
precipitation          0.087191
temperature            0.066573
wind_speed             0.052193
DEPARTURE_MINUTE       0.045069
SECURITY_DELAY         0.043961
snowfall               0.041985
DAY_OF_WEEK            0.028634
MONTH                  0.023087
IS_HOLIDAY_PERIOD      0.019809
DISTANCE               0.015374
CRS_ELAPSED_TIME       0.014881
DISTANCE_GROUP         0.013999
ORIGIN_STATE_ABR       0.007333
DEST_STATE_ABR         0.005608
OP_CARRIER_FL_NUM      0.001742
DAY_OF_MONTH           0.001539
YEAR                  -0.002030
OP_UNIQUE_CARRIER     -0.010214
Name: DELAYED, dtype: float64

In [81]:
# Drop the Delay columns
df = df.drop(columns=['DEP_DELAY_NEW', 'DEP_DELAY', 'LATE_AIRCRAFT_DELAY', 'CARRIER_DELAY', 'NAS_DELAY', 'WEATHER_DELAY', 'SECURITY_DELAY'])

In [82]:
updated_correlation_matrix = df.corr(numeric_only=True, method='spearman')
updated_numerical_columns = updated_correlation_matrix['DELAYED'].sort_values(ascending=False)
updated_numerical_columns

DELAYED              1.000000
DEPARTURE_HOUR       0.197426
precipitation        0.087191
temperature          0.066573
wind_speed           0.052193
DEPARTURE_MINUTE     0.045069
snowfall             0.041985
DAY_OF_WEEK          0.028634
MONTH                0.023087
IS_HOLIDAY_PERIOD    0.019809
DISTANCE             0.015374
CRS_ELAPSED_TIME     0.014881
DISTANCE_GROUP       0.013999
ORIGIN_STATE_ABR     0.007333
DEST_STATE_ABR       0.005608
OP_CARRIER_FL_NUM    0.001742
DAY_OF_MONTH         0.001539
YEAR                -0.002030
OP_UNIQUE_CARRIER   -0.010214
Name: DELAYED, dtype: float64

In [83]:
updated_numerical_columns = updated_numerical_columns.drop(['DELAYED', 'DEPARTURE_MINUTE', 'DISTANCE_GROUP', 'OP_CARRIER_FL_NUM', 'DAY_OF_MONTH', 'YEAR'])

In [84]:
updated_numerical_columns

DEPARTURE_HOUR       0.197426
precipitation        0.087191
temperature          0.066573
wind_speed           0.052193
snowfall             0.041985
DAY_OF_WEEK          0.028634
MONTH                0.023087
IS_HOLIDAY_PERIOD    0.019809
DISTANCE             0.015374
CRS_ELAPSED_TIME     0.014881
ORIGIN_STATE_ABR     0.007333
DEST_STATE_ABR       0.005608
OP_UNIQUE_CARRIER   -0.010214
Name: DELAYED, dtype: float64

In [ ]:
numerical_features = updated_numerical_columns.index.tolist()

In [86]:
numerical_features.append('ORIGIN')
numerical_features.append('DEST')
numerical_features.append('ROUTE')

In [ ]:
# ['DEPARTURE_HOUR', 'DAY_OF_WEEK', 'MONTH', 'IS_HOLIDAY_PERIOD', 'DISTANCE', 'CRS_ELAPSED_TIME', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR', 'OP_UNIQUE_CARRIER', 'CARRIER_DELAY_RATE', 'ORIGIN_DELAY_RATE', 'ROUTE_DELAY_RATE', 'ORIGIN_ENCODED', 'DEST_ENCODED', 'ROUTE_ENCODED']

### 10. Feature engineering congestion columns

In [87]:
# ORIGIN_HOURLY_FLIGHTS - How many flights departed from that origin airport in that hour
df['ORIGIN_HOURLY_FLIGHTS'] = df.groupby(['ORIGIN', 'FL_DATE', 'DEPARTURE_HOUR'])['ORIGIN'].transform('count')

# ROUTE_HOURLY_FLIGHTS - How many flights operated on that route in that hour
df['ROUTE_HOURLY_FLIGHTS'] = df.groupby(['ROUTE', 'FL_DATE', 'DEPARTURE_HOUR'])['ROUTE'].transform('count')

In [88]:
numerical_features.append('ORIGIN_HOURLY_FLIGHTS')
numerical_features.append('ROUTE_HOURLY_FLIGHTS')

In [89]:
X = df[numerical_features]

### 11.  Train/val/test split -- 70/15/15

In [231]:
numerical_features

['DEPARTURE_HOUR',
 'precipitation',
 'temperature',
 'wind_speed',
 'snowfall',
 'DAY_OF_WEEK',
 'MONTH',
 'IS_HOLIDAY_PERIOD',
 'DISTANCE',
 'CRS_ELAPSED_TIME',
 'ORIGIN_STATE_ABR',
 'DEST_STATE_ABR',
 'OP_UNIQUE_CARRIER',
 'ORIGIN',
 'DEST',
 'ROUTE',
 'ORIGIN_HOURLY_FLIGHTS',
 'ROUTE_HOURLY_FLIGHTS']

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=1234)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=1234)

In [92]:
print(f"Train: {X_train.shape[0]:,} rows")
print(f"Validation: {X_val.shape[0]:,} rows")
print(f"Test: {X_test.shape[0]:,} rows")

Train: 6,357,794 rows
Validation: 1,362,384 rows
Test: 1,362,385 rows

### 12. Feature engineering historical delay columns

In [93]:
carrier_delay_map = pd.concat([X_train, y_train], axis=1).groupby('OP_UNIQUE_CARRIER')['DELAYED'].mean()
origin_delay_map = pd.concat([X_train, y_train], axis=1).groupby('ORIGIN')['DELAYED'].mean()
route_delay_map = pd.concat([X_train, y_train], axis=1).groupby('ROUTE')['DELAYED'].mean()

# CARRIER_DELAY_RATE - percentage of flights that were delayed for a specific airline. 
X_train['CARRIER_DELAY_RATE'] = X_train['OP_UNIQUE_CARRIER'].map(carrier_delay_map)
X_val['CARRIER_DELAY_RATE'] = X_val['OP_UNIQUE_CARRIER'].map(carrier_delay_map)
X_test['CARRIER_DELAY_RATE'] = X_test['OP_UNIQUE_CARRIER'].map(carrier_delay_map)

# ORIGIN_DELAY_RATE - percentage of flights that were delayed departing from a specific airport. 
X_train['ORIGIN_DELAY_RATE'] = X_train['ORIGIN'].map(origin_delay_map)
X_val['ORIGIN_DELAY_RATE'] = X_val['ORIGIN'].map(origin_delay_map)
X_test['ORIGIN_DELAY_RATE'] = X_test['ORIGIN'].map(origin_delay_map)

# ROUTE_DELAY_RATE - percentage of flights that were delayed on a specific route. 
X_train['ROUTE_DELAY_RATE'] = X_train['ROUTE'].map(route_delay_map)
X_val['ROUTE_DELAY_RATE'] = X_val['ROUTE'].map(route_delay_map)
X_test['ROUTE_DELAY_RATE'] = X_test['ROUTE'].map(route_delay_map)

### 13. Target encode ORIGIN, DEST, ROUTE on training data only

In [94]:
from sklearn.preprocessing import TargetEncoder

In [95]:
te_origin = TargetEncoder()
te_dest = TargetEncoder()
te_route = TargetEncoder()

In [96]:
# Fit transform the training data
X_train['ORIGIN_ENCODED'] = te_origin.fit_transform(X_train[['ORIGIN']], y_train)
X_train['DEST_ENCODED'] = te_dest.fit_transform(X_train[['DEST']], y_train)
X_train['ROUTE_ENCODED'] = te_route.fit_transform(X_train[['ROUTE']], y_train)

X_val['ORIGIN_ENCODED'] = te_origin.transform(X_val[['ORIGIN']])
X_val['DEST_ENCODED'] = te_dest.transform(X_val[['DEST']])
X_val['ROUTE_ENCODED'] = te_route.transform(X_val[['ROUTE']])

X_test['ORIGIN_ENCODED'] = te_origin.transform(X_test[['ORIGIN']])
X_test['DEST_ENCODED'] = te_dest.transform(X_test[['DEST']])
X_test['ROUTE_ENCODED'] = te_route.transform(X_test[['ROUTE']])

X_train = X_train.drop(columns=['ORIGIN', 'DEST', 'ROUTE'])
X_val = X_val.drop(columns=['ORIGIN', 'DEST', 'ROUTE'])
X_test = X_test.drop(columns=['ORIGIN', 'DEST', 'ROUTE'])

In [97]:
print('OP_UNIQUE_CARRIER' in X_train.columns)

True

### 14. Saved processed data to parquet

In [98]:
# Saving the origin, dest, and route target encoders
joblib.dump(te_origin, '../encodings/origin_te.pkl')
joblib.dump(te_dest, '../encodings/dest_te.pkl')
joblib.dump(te_route, '../encodings/route_te.pkl')

['../encodings/route_te.pkl']

In [99]:
# Saving the training, validation, and testing data
X_train.to_parquet('../data/X_train.parquet')
X_val.to_parquet('../data/X_val.parquet')
X_test.to_parquet('../data/X_test.parquet')
y_train.to_frame().to_parquet('../data/y_train.parquet')
y_val.to_frame().to_parquet('../data/y_val.parquet')
y_test.to_frame().to_parquet('../data/y_test.parquet')

## Modeling

In [188]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix, roc_auc_score

In [189]:
import lightgbm as lgbm
import optuna

In [190]:
X_sample, _, y_sample, _ = train_test_split(X_train, y_train, train_size=0.1, stratify=y_train, random_state=1234)
X_s_train, X_s_val, y_s_train, y_s_val = train_test_split(X_sample, y_sample, test_size=0.2)

In [203]:
training_data = lgbm.Dataset(X_s_train, label=y_s_train, params={'feature_pre_filter': False})
validation_data = lgbm.Dataset(X_s_val, label=y_s_val, reference=training_data, params={'feature_pre_filter': False})

### 1. Hyperparameter Tuning

In [258]:
def objective(trial):
    params = {
        "objective": "binary",
        "metric": "auc",
        "verbosity": -1,
        "n_jobs": -1,
        "is_unbalance": True,
        
        "learning_rate": trial.suggest_float("learning_rate", 0.03, 0.10),
        "num_leaves": trial.suggest_int("num_leaves", 150, 300),
        "max_depth": trial.suggest_int("max_depth", 10, 14),
        "min_child_samples": trial.suggest_int("min_child_samples", 50, 200),
        "lambda_l1": trial.suggest_float("lambda_l1", 1e-3, 10.0, log=True),
        "lambda_l2": trial.suggest_float("lambda_l2", 1e-3, 10.0, log=True)
    }
    
    callbacks = [lgbm.early_stopping(stopping_rounds=30, verbose=False)]
    
    model = lgbm.train(
        params, 
        training_data, 
        valid_sets=[validation_data],
        num_boost_round=1000,
        callbacks=callbacks
    )
    
    return model.best_score["valid_0"]["auc"]

In [259]:
study = optuna.create_study(direction="maximize")

[I 2026-06-25 13:44:01,884] A new study created in memory with name: no-name-90ad4290-7328-4c36-befc-583ddcfc3e90

In [260]:
study.optimize(objective, n_trials=30)

[I 2026-06-25 13:44:27,797] Trial 0 finished with value: 0.7175722571995103 and parameters: {'learning_rate': 0.083864803592384, 'num_leaves': 158, 'max_depth': 10, 'min_child_samples': 62, 'lambda_l1': 0.3520525755393529, 'lambda_l2': 6.557780333257904}. Best is trial 0 with value: 0.7175722571995103.
[I 2026-06-25 13:44:36,025] Trial 1 finished with value: 0.7176168753021598 and parameters: {'learning_rate': 0.09028338870003198, 'num_leaves': 250, 'max_depth': 11, 'min_child_samples': 65, 'lambda_l1': 4.60895613769056, 'lambda_l2': 0.032601232670415085}. Best is trial 1 with value: 0.7176168753021598.
[I 2026-06-25 13:44:46,261] Trial 2 finished with value: 0.7179622438890881 and parameters: {'learning_rate': 0.04379816653968756, 'num_leaves': 153, 'max_depth': 11, 'min_child_samples': 105, 'lambda_l1': 0.14996997648585791, 'lambda_l2': 0.3949118888161553}. Best is trial 2 with value: 0.7179622438890881.
[I 2026-06-25 13:44:59,001] Trial 3 finished with value: 0.7188184926301321 and parameters: {'learning_rate': 0.05307198052350012, 'num_leaves': 278, 'max_depth': 13, 'min_child_samples': 111, 'lambda_l1': 0.05227087574250966, 'lambda_l2': 5.457411874629042}. Best is trial 3 with value: 0.7188184926301321.
[I 2026-06-25 13:45:10,276] Trial 4 finished with value: 0.7185932155486849 and parameters: {'learning_rate': 0.041360882381612944, 'num_leaves': 209, 'max_depth': 12, 'min_child_samples': 173, 'lambda_l1': 2.8465336574032416, 'lambda_l2': 0.06252979317657262}. Best is trial 3 with value: 0.7188184926301321.
[I 2026-06-25 13:45:16,006] Trial 5 finished with value: 0.7171506171635978 and parameters: {'learning_rate': 0.08741325593445194, 'num_leaves': 251, 'max_depth': 10, 'min_child_samples': 63, 'lambda_l1': 1.0865870364122685, 'lambda_l2': 1.1595563951466707}. Best is trial 3 with value: 0.7188184926301321.
[I 2026-06-25 13:45:34,359] Trial 6 finished with value: 0.7194081850124374 and parameters: {'learning_rate': 0.03586716772848204, 'num_leaves': 172, 'max_depth': 14, 'min_child_samples': 167, 'lambda_l1': 0.005213877408317814, 'lambda_l2': 0.007468545797578087}. Best is trial 6 with value: 0.7194081850124374.
[I 2026-06-25 13:45:48,024] Trial 7 finished with value: 0.7188011934938032 and parameters: {'learning_rate': 0.044791803431222105, 'num_leaves': 285, 'max_depth': 10, 'min_child_samples': 155, 'lambda_l1': 0.04909022382461232, 'lambda_l2': 0.0068853852302710305}. Best is trial 6 with value: 0.7194081850124374.
[I 2026-06-25 13:46:02,762] Trial 8 finished with value: 0.7187275844967158 and parameters: {'learning_rate': 0.03526487653233823, 'num_leaves': 169, 'max_depth': 13, 'min_child_samples': 172, 'lambda_l1': 8.3625760647842, 'lambda_l2': 0.006347429630023522}. Best is trial 6 with value: 0.7194081850124374.
[I 2026-06-25 13:46:11,903] Trial 9 finished with value: 0.7184633611605958 and parameters: {'learning_rate': 0.060548819202158856, 'num_leaves': 223, 'max_depth': 13, 'min_child_samples': 102, 'lambda_l1': 0.20000355603569786, 'lambda_l2': 1.6514864982001474}. Best is trial 6 with value: 0.7194081850124374.
[I 2026-06-25 13:46:18,855] Trial 10 finished with value: 0.718417510120428 and parameters: {'learning_rate': 0.07044033980654087, 'num_leaves': 195, 'max_depth': 14, 'min_child_samples': 197, 'lambda_l1': 0.001049929885904693, 'lambda_l2': 0.0013986867577436568}. Best is trial 6 with value: 0.7194081850124374.
[I 2026-06-25 13:46:29,982] Trial 11 finished with value: 0.7185678344016468 and parameters: {'learning_rate': 0.05600090344397257, 'num_leaves': 299, 'max_depth': 14, 'min_child_samples': 129, 'lambda_l1': 0.008160512108289055, 'lambda_l2': 0.21057192596449278}. Best is trial 6 with value: 0.7194081850124374.
[I 2026-06-25 13:46:49,558] Trial 12 finished with value: 0.7191615347159488 and parameters: {'learning_rate': 0.03178165373600332, 'num_leaves': 264, 'max_depth': 13, 'min_child_samples': 131, 'lambda_l1': 0.007875785337138895, 'lambda_l2': 7.505704757902609}. Best is trial 6 with value: 0.7194081850124374.
[I 2026-06-25 13:47:13,766] Trial 13 finished with value: 0.7194229623750962 and parameters: {'learning_rate': 0.03003408684781928, 'num_leaves': 185, 'max_depth': 14, 'min_child_samples': 141, 'lambda_l1': 0.004433675696071245, 'lambda_l2': 0.001024217412282968}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:47:31,243] Trial 14 finished with value: 0.7193176629522473 and parameters: {'learning_rate': 0.03280859746400386, 'num_leaves': 183, 'max_depth': 14, 'min_child_samples': 151, 'lambda_l1': 0.0014029377945615044, 'lambda_l2': 0.0011769572162486823}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:47:44,762] Trial 15 finished with value: 0.7192688217078637 and parameters: {'learning_rate': 0.04832875346216389, 'num_leaves': 184, 'max_depth': 14, 'min_child_samples': 191, 'lambda_l1': 0.006538603120366433, 'lambda_l2': 0.006599589109171502}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:48:03,340] Trial 16 finished with value: 0.7194184865715401 and parameters: {'learning_rate': 0.030676836297976576, 'num_leaves': 217, 'max_depth': 14, 'min_child_samples': 145, 'lambda_l1': 0.003377301897666359, 'lambda_l2': 0.003245579372657607}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:48:23,036] Trial 17 finished with value: 0.7193062117445895 and parameters: {'learning_rate': 0.03015186867837316, 'num_leaves': 230, 'max_depth': 12, 'min_child_samples': 132, 'lambda_l1': 0.028559888207490128, 'lambda_l2': 0.0027261925185498386}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:48:30,365] Trial 18 finished with value: 0.717941586921866 and parameters: {'learning_rate': 0.06734364198077995, 'num_leaves': 207, 'max_depth': 13, 'min_child_samples': 80, 'lambda_l1': 0.002601425390088263, 'lambda_l2': 0.023110869789276435}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:48:46,634] Trial 19 finished with value: 0.7190355947228102 and parameters: {'learning_rate': 0.0389767284537139, 'num_leaves': 231, 'max_depth': 12, 'min_child_samples': 144, 'lambda_l1': 0.0206466219695628, 'lambda_l2': 0.002426642526241211}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:48:59,007] Trial 20 finished with value: 0.7191988161229976 and parameters: {'learning_rate': 0.05007773846380696, 'num_leaves': 207, 'max_depth': 14, 'min_child_samples': 120, 'lambda_l1': 0.01766237692143606, 'lambda_l2': 0.019820641862641396}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:49:15,071] Trial 21 finished with value: 0.7191493335349629 and parameters: {'learning_rate': 0.0380122632590797, 'num_leaves': 174, 'max_depth': 14, 'min_child_samples': 172, 'lambda_l1': 0.0032789155778471927, 'lambda_l2': 0.0031312598910644496}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:49:31,122] Trial 22 finished with value: 0.718929092361376 and parameters: {'learning_rate': 0.03775055317650351, 'num_leaves': 194, 'max_depth': 14, 'min_child_samples': 160, 'lambda_l1': 0.002815606017613612, 'lambda_l2': 0.012182179607325082}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:49:48,536] Trial 23 finished with value: 0.7190450740130193 and parameters: {'learning_rate': 0.03111864105804761, 'num_leaves': 168, 'max_depth': 14, 'min_child_samples': 142, 'lambda_l1': 0.005028171311798956, 'lambda_l2': 0.0012145580424858505}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:49:54,722] Trial 24 finished with value: 0.7174001913312577 and parameters: {'learning_rate': 0.09904487639426607, 'num_leaves': 192, 'max_depth': 13, 'min_child_samples': 163, 'lambda_l1': 0.01032552906535415, 'lambda_l2': 0.0038875625761736737}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:50:06,774] Trial 25 finished with value: 0.7188336499171676 and parameters: {'learning_rate': 0.0421328018016991, 'num_leaves': 212, 'max_depth': 14, 'min_child_samples': 184, 'lambda_l1': 0.001953575318966636, 'lambda_l2': 0.049509476757571384}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:50:22,068] Trial 26 finished with value: 0.7190883699266661 and parameters: {'learning_rate': 0.036261538590753296, 'num_leaves': 178, 'max_depth': 13, 'min_child_samples': 91, 'lambda_l1': 0.013816319141977937, 'lambda_l2': 0.011767358723739315}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:50:31,522] Trial 27 finished with value: 0.7182038694574431 and parameters: {'learning_rate': 0.045420357099866165, 'num_leaves': 162, 'max_depth': 14, 'min_child_samples': 143, 'lambda_l1': 0.004920081308729171, 'lambda_l2': 0.0021889021104049096}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:50:50,657] Trial 28 finished with value: 0.7186726952065543 and parameters: {'learning_rate': 0.030419489222989014, 'num_leaves': 222, 'max_depth': 13, 'min_child_samples': 124, 'lambda_l1': 0.04019194920584688, 'lambda_l2': 0.005044700479145992}. Best is trial 13 with value: 0.7194229623750962.
[I 2026-06-25 13:50:59,495] Trial 29 finished with value: 0.7182951209947958 and parameters: {'learning_rate': 0.05926321841622955, 'num_leaves': 152, 'max_depth': 14, 'min_child_samples': 186, 'lambda_l1': 0.0010968301843439477, 'lambda_l2': 0.011291918442368924}. Best is trial 13 with value: 0.7194229623750962.

### 2. Best Parameters

In [261]:
print("Best Params:", study.best_params)

Best Params: {'learning_rate': 0.03003408684781928, 'num_leaves': 185, 'max_depth': 14, 'min_child_samples': 141, 'lambda_l1': 0.004433675696071245, 'lambda_l2': 0.001024217412282968}

In [262]:
print("Best Score:", study.best_value)

Best Score: 0.7194229623750962

In [263]:
best_params = study.best_params

In [264]:
best_value = study.best_value

In [265]:
best_trial = study.best_trial

In [266]:
print("Best Params:", best_params)
print("Best Score:", best_value)

Best Params: {'learning_rate': 0.03003408684781928, 'num_leaves': 185, 'max_depth': 14, 'min_child_samples': 141, 'lambda_l1': 0.004433675696071245, 'lambda_l2': 0.001024217412282968}
Best Score: 0.7194229623750962

### 4. Train Best Model

In [267]:
best_model = lgbm.LGBMClassifier(**best_params, objective="binary", metric="auc", verbosity=-1, n_jobs=-1, is_unbalance=True)

In [268]:
best_model.fit(X_train, y_train)

LGBMClassifier(is_unbalance=True, lambda_l1=0.004433675696071245,
               lambda_l2=0.001024217412282968,
               learning_rate=0.03003408684781928, max_depth=14, metric='auc',
               min_child_samples=141, n_jobs=-1, num_leaves=185,
               objective='binary', verbosity=-1)

In [269]:
y_val_auc = best_model.predict_proba(X_val)[:, 1]
y_val_auc

array([0.19111885, 0.44147608, 0.49900356, ..., 0.45211395, 0.55744887,
       0.5207848 ], shape=(1362384,))

In [270]:
print(f"Validation AUC-ROC: {roc_auc_score(y_val, y_val_auc)}")

Validation AUC-ROC: 0.7079664130905766

In [272]:
y_test_auc = best_model.predict_proba(X_test)[:, 1]
print(f"Testing AUC-ROC: {roc_auc_score(y_test, y_test_auc)}")

Testing AUC-ROC: 0.7073903658077865

In [273]:
y_val_pred = best_model.predict(X_val)
y_val_accuracy = accuracy_score(y_val, y_val_pred)
print(f"Validation accuracy: {y_val_accuracy}")

Validation accuracy: 0.6644095937709192

In [275]:
y_test_pred = best_model.predict(X_test)
y_test_accuracy = accuracy_score(y_test, y_test_pred)
print(f"Testing accuracy: {y_test_accuracy}")

Testing accuracy: 0.6642043181626339

In [277]:
from sklearn.metrics import precision_score, recall_score, f1_score

val_precision = precision_score(y_val, y_val_pred, average='weighted')
val_recall = recall_score(y_val, y_val_pred, average='weighted')
val_f1 = f1_score(y_val, y_val_pred, average='weighted')

print(f"Precision: {val_precision:.4f}")
print(f"Recall: {val_recall:.4f}")
print(f"F1: {val_f1:.4f}")

Precision: 0.7599
Recall: 0.6644
F1: 0.6931

In [278]:
test_precision = precision_score(y_test, y_test_pred, average='weighted')
test_recall = recall_score(y_test, y_test_pred, average='weighted')
test_f1 = f1_score(y_test, y_test_pred, average='weighted')

print(f"Precision: {test_precision:.4f}")
print(f"Recall: {test_recall:.4f}")
print(f"F1: {test_f1:.4f}")

Precision: 0.7597
Recall: 0.6642
F1: 0.6929

In [280]:
cm = confusion_matrix(y_test, y_test_pred)
print(cm)

[[725815 350638]
 [106845 179087]]

In [281]:
cr = classification_report(y_test, y_test_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.87      0.67      0.76   1076453
           1       0.34      0.63      0.44    285932

    accuracy                           0.66   1362385
   macro avg       0.60      0.65      0.60   1362385
weighted avg       0.76      0.66      0.69   1362385

In [282]:
joblib.dump(best_model, '../data/best_model.pkl')

['../data/best_model.pkl']